### ISSUE TITLE
Incorrect RakNet magic sequence in `pieraknet.buffer.Buffer.write_magic`

### ISSUE THREAD

**Issue by walnutmusic740** [PieMC-Dev/PieRakNet#24]
Hello! I have noticed that the RakNet magic sequence supplied as a default value to `pieraknet.buffer.Buffer.write_magic` is incorrect. The sequence contains one extra byte (therefore causing a `ValueError` to be raised) at index 26. I suggest that you replace the sequence (`b'00ffff00fefefefefdfdfdfd122345678'`) with a valid sequence (`b'00ffff00fefefefefdfdfdfd12345678'`).

**Comment by andiricum2** [comment]
Fixed. Thanks :)
