### ISSUE TITLE
Incorrect offline_Pong

### ISSUE THREAD

**Issue by skyss0fly-pm-pl** [PieMC-Dev/PieRakNet#6]
Raknet as you know has its offline_pong/ disconnect pong as 0x1c
In minecraft bedrock protocol it is known as "Add Mob Effect" so we have an incorrect pong?
I will provide screenshots on discord under bugs thread and link here

**Comment by MFDGaming** [comment]
> Raknet as you know has its offline_pong/ disconnect pong as 0x1c In minecraft bedrock protocol it is known as "Add Mob Effect" so we have an incorrect pong? I will provide screenshots on discord under bugs thread and link here

The raknet packet IDs have nothing to do with the minecraft ones, so this issue must close

**Comment by lapismyt** [comment]
Unconnected Pong is RakNet packet, not Minecraft game packet. 0x1c will be "Add Mob Effect" only when it's inside GamePacket.

[Unconnected Pong Specification](https://wiki.vg/Raknet_Protocol#Unconnected_Pong)
